[general]
import = [
    "~/.config/alacritty/themes/themes/dawnfox.toml", 
]

[window]
option_as_alt =  "Both"
#startup_mode = "fullscreen"

[font]
size = 14.0
normal = { family = "Explex Console NF", style = "Regular" }

[env]
 TERM = "alacritty"

[terminal]
shell = "fish"
