-- Barbar (buffer tabs) configuration
require("barbar").setup({})

local map = vim.keymap.set
map("n", "<A-,>", "<Cmd>BufferPrevious<CR>", { desc = "Previous buffer" })
map("n", "<A-.>", "<Cmd>BufferNext<CR>", { desc = "Next buffer" })
map("n", "<A-<>", "<Cmd>BufferMovePrevious<CR>", { desc = "Move buffer previous" })
map("n", "<A->>", "<Cmd>BufferMoveNext<CR>", { desc = "Move buffer next" })
map("n", "<A-1>", "<Cmd>BufferGoto 1<CR>", { desc = "Go to buffer 1" })
map("n", "<A-2>", "<Cmd>BufferGoto 2<CR>", { desc = "Go to buffer 2" })
map("n", "<A-3>", "<Cmd>BufferGoto 3<CR>", { desc = "Go to buffer 3" })
map("n", "<A-4>", "<Cmd>BufferGoto 4<CR>", { desc = "Go to buffer 4" })
map("n", "<A-5>", "<Cmd>BufferGoto 5<CR>", { desc = "Go to buffer 5" })
map("n", "<A-6>", "<Cmd>BufferGoto 6<CR>", { desc = "Go to buffer 6" })
map("n", "<A-7>", "<Cmd>BufferGoto 7<CR>", { desc = "Go to buffer 7" })
map("n", "<A-8>", "<Cmd>BufferGoto 8<CR>", { desc = "Go to buffer 8" })
map("n", "<A-9>", "<Cmd>BufferGoto 9<CR>", { desc = "Go to buffer 9" })
map("n", "<A-0>", "<Cmd>BufferLast<CR>", { desc = "Go to last buffer" })
map("n", "<A-p>", "<Cmd>BufferPin<CR>", { desc = "Pin/unpin buffer" })
map("n", "<A-c>", "<Cmd>BufferClose<CR>", { desc = "Close buffer" })
map("n", "<C-p>", "<Cmd>BufferPick<CR>", { desc = "Pick buffer" })
map("n", "<Space>bb", "<Cmd>BufferOrderByBufferNumber<CR>", { desc = "Order by buffer number" })
map("n", "<Space>bn", "<Cmd>BufferOrderByName<CR>", { desc = "Order by name" })
map("n", "<Space>bd", "<Cmd>BufferOrderByDirectory<CR>", { desc = "Order by directory" })
map("n", "<Space>bl", "<Cmd>BufferOrderByLanguage<CR>", { desc = "Order by language" })
map("n", "<Space>bw", "<Cmd>BufferOrderByWindowNumber<CR>", { desc = "Order by window number" })
