# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  arto-vim = {
    pname = "arto-vim";
    version = "5a00f0e977a035f8b098e0c4142e968a64f8efd2";
    src = fetchFromGitHub {
      owner = "arto-app";
      repo = "arto.vim";
      rev = "5a00f0e977a035f8b098e0c4142e968a64f8efd2";
      fetchSubmodules = false;
      sha256 = "sha256-Pet/wjh0Pv6HMPRKPsgNktpMIjqwiFW2zr/IeZ5Ht84=";
    };
    date = "2026-03-28";
  };
  blink-cmp-dictionary = {
    pname = "blink-cmp-dictionary";
    version = "898a958cece34da20524d04ebc032a92a9565643";
    src = fetchFromGitHub {
      owner = "Kaiser-Yang";
      repo = "blink-cmp-dictionary";
      rev = "898a958cece34da20524d04ebc032a92a9565643";
      fetchSubmodules = false;
      sha256 = "sha256-eV0/8ga2ZE0HLrFN24k6MIGFNl/3zSr6/nqF8MwDDmQ=";
    };
    date = "2026-06-01";
  };
  blink-cmp-skkeleton = {
    pname = "blink-cmp-skkeleton";
    version = "bc9391a8767e9cdfed2a603b6f49699c4ccc6e26";
    src = fetchFromGitHub {
      owner = "Xantibody";
      repo = "blink-cmp-skkeleton";
      rev = "bc9391a8767e9cdfed2a603b6f49699c4ccc6e26";
      fetchSubmodules = false;
      sha256 = "sha256-teQAXiKfFtsRfewtliHjyiwv+u96cbOpx4FolpQa5WE=";
    };
    date = "2026-07-21";
  };
  in-and-out = {
    pname = "in-and-out";
    version = "03456b9c49365a28732378a7f2a72a613154e042";
    src = fetchFromGitHub {
      owner = "ysmb-wtsg";
      repo = "in-and-out.nvim";
      rev = "03456b9c49365a28732378a7f2a72a613154e042";
      fetchSubmodules = false;
      sha256 = "sha256-QPEvWOTKzscUs+vHQ0LJ/BNBd9buMgG/jkmjg7JlhT8=";
    };
    date = "2025-08-16";
  };
  neogit = {
    pname = "neogit";
    version = "73870229977fdd8747025820e15e98cfde787b9c";
    src = fetchFromGitHub {
      owner = "Xantibody";
      repo = "neogit";
      rev = "73870229977fdd8747025820e15e98cfde787b9c";
      fetchSubmodules = false;
      sha256 = "sha256-tvIJEHv/R8I1W3FBAwZHmn92JgiibqQtR75V9wQFSsE=";
    };
    date = "2026-01-24";
  };
  nvim-markdown = {
    pname = "nvim-markdown";
    version = "37850581fdaec153ce84af677d43bf8fce60813a";
    src = fetchFromGitHub {
      owner = "ixru";
      repo = "nvim-markdown";
      rev = "37850581fdaec153ce84af677d43bf8fce60813a";
      fetchSubmodules = false;
      sha256 = "sha256-wjYTO9WqdDEbH4L3dsHqOoeQf0y/Uo6WX94w/D4EuGU=";
    };
    date = "2025-11-02";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "72e6425966232a01ed9bd70b24e2fd1dddc4d368";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "72e6425966232a01ed9bd70b24e2fd1dddc4d368";
      fetchSubmodules = false;
      sha256 = "sha256-vowvXdNy5J2uLxBt9xLF6/0HYbl3yYv6vWl51AQ9+Ic=";
    };
    date = "2026-07-21";
  };
  smooth-cursor = {
    pname = "smooth-cursor";
    version = "12518b284e1e3f7c6c703b346815968e1620bee2";
    src = fetchFromGitHub {
      owner = "gen740";
      repo = "SmoothCursor.nvim";
      rev = "12518b284e1e3f7c6c703b346815968e1620bee2";
      fetchSubmodules = false;
      sha256 = "sha256-P0jGm5ODEVbtmqPGgDFBPDeuOF49CFq5x1PzubEJgaM=";
    };
    date = "2024-09-18";
  };
  tiny-code-action = {
    pname = "tiny-code-action";
    version = "0d040ed81f7953118b81cd12681fcdfcac069803";
    src = fetchFromGitHub {
      owner = "rachartier";
      repo = "tiny-code-action.nvim";
      rev = "0d040ed81f7953118b81cd12681fcdfcac069803";
      fetchSubmodules = false;
      sha256 = "sha256-UF9zeO5Uujdt2MEwy2d2Lhk6JRnEN4vrEvYslv0/zaA=";
    };
    date = "2026-04-25";
  };
  tiny-glimmer = {
    pname = "tiny-glimmer";
    version = "9a48d8a7436231cb16d47c88f924702e5602870a";
    src = fetchFromGitHub {
      owner = "rachartier";
      repo = "tiny-glimmer.nvim";
      rev = "9a48d8a7436231cb16d47c88f924702e5602870a";
      fetchSubmodules = false;
      sha256 = "sha256-ONv/NE4D5vWNV56oJc/h5/nniOWjH5eUG0Q80dMVSxg=";
    };
    date = "2026-07-05";
  };
  tiny-inline-diagnostic = {
    pname = "tiny-inline-diagnostic";
    version = "6264451f14119d63a52580e5198d6baf8518b0b2";
    src = fetchFromGitHub {
      owner = "rachartier";
      repo = "tiny-inline-diagnostic.nvim";
      rev = "6264451f14119d63a52580e5198d6baf8518b0b2";
      fetchSubmodules = false;
      sha256 = "sha256-dG4eCcIRaHOPj75DNOBJAqo2Vy7LAQ0QfWOVD94FloA=";
    };
    date = "2026-07-05";
  };
  vim-qfreplace = {
    pname = "vim-qfreplace";
    version = "707a895f9f86eeed106f64da0bd9fa07b3cd9cee";
    src = fetchFromGitHub {
      owner = "thinca";
      repo = "vim-qfreplace";
      rev = "707a895f9f86eeed106f64da0bd9fa07b3cd9cee";
      fetchSubmodules = false;
      sha256 = "sha256-6G89NznCOumLIJb2l8szKGIWMr3CtpeHUfdkzEOCo8U=";
    };
    date = "2024-06-14";
  };
}
