name: Build

on:
  pull_request:

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      skip_build: ${{ steps.check.outputs.skip_build }}
    steps:
      - id: check
        run: |
          branch="${GITHUB_HEAD_REF}"
          if [[ "$branch" == renovate/darwin ]]; then
            echo "skip_build=true" >> "$GITHUB_OUTPUT"
          else
            echo "skip_build=false" >> "$GITHUB_OUTPUT"
          fi

  nixos-build:
    needs: detect
    if: needs.detect.outputs.skip_build == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build .#nixosConfigurations.E14Gen6.config.system.build.toplevel

  darwin-skip:
    needs: detect
    if: needs.detect.outputs.skip_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake show
